[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/pi/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    10.0.0.0/16
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz
    
[octoprint_compat]

[history]

[file_manager]
enable_object_processing: True

[update_manager]
channel: dev
refresh_interval: 168

[update_manager mainsail-config]
type: git_repo
primary_branch: master
path: ~/mainsail-config
origin: https://github.com/mainsail-crew/mainsail-config.git
managed_services: klipper

[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: ~/mainsail

[mqtt]
address: 127.0.0.1
client_id: v0-pi
instance_name: v0-pi
enable_moonraker_api: false
publish_split_status: False
status_interval: 1
status_objects:
    webhooks
    printer
    toolhead
    extruder
    heater_bed
    fan
    temperature_sensor chamber
    temperature_sensor chamber_pcb
    temperature_sensor mcu_temp
    temperature_sensor raspberry_pi
    
[update_manager spyglass]
type: git_repo
channel: beta
path: ~/spyglass
origin: https://github.com/mryel00/spyglass.git
managed_services: spyglass
primary_branch: main

[notifier all]
url: tgram://{secrets.v0.bot_token}/{secrets.v0.chat_id}
events: *
body: "Your printer status has changed to {event_name}"
attach: http://127.0.0.1/webcam/snapshot

#[notifier all1]
#url: pover://{secrets.pushover.user}@{secrets.pushover.token}
#events: *
#body: "Your printer status has changed to {event_name}"

[update_manager mobileraker]
install_script: /home/pi/mobileraker_companion/scripts/install.sh
requirements: /home/pi/mobileraker_companion/scripts/mobileraker-requirements.txt
env: /home/pi/mobileraker-env/bin/python
managed_services: mobileraker
primary_branch: main
origin: https://github.com/Clon1998/mobileraker_companion.git
path: /home/pi/mobileraker_companion
type: git_repo

[update_manager Klipper-Adaptive-Meshing-Purging]
type: git_repo
channel: dev
path: ~/Klipper-Adaptive-Meshing-Purging
origin: https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services: klipper
primary_branch: main
